# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
            ${LAYERDIR}/appends/*/*.bbappend \
            "

BBFILE_COLLECTIONS += "meta-textbook-application"
BBFILE_PATTERN_meta-textbook-application = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-textbook-application = "6"

LAYERDEPENDS_meta-textbook-application = "core"
LAYERSERIES_COMPAT_meta-textbook-application = "scarthgap"
