# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-textbook-selinux"
BBFILE_PATTERN_meta-textbook-selinux = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-textbook-selinux = "6"

LAYERDEPENDS_meta-textbook-selinux = "core"
LAYERSERIES_COMPAT_meta-textbook-selinux = "scarthgap"

# Include the SELinux feature configuration
# to apply the necessary settings
# for enabling SELinux support in the build.
require conf/feature/textbook-selinux-feature.conf
