# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-textbook-external"
BBFILE_PATTERN_meta-textbook-external = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-textbook-external = "6"

LAYERDEPENDS_meta-textbook-external = "core"
LAYERSERIES_COMPAT_meta-textbook-external = "scarthgap"
