# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
            ${LAYERDIR}/appends/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-textbook-sdk"
BBFILE_PATTERN_meta-textbook-sdk = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-textbook-sdk = "6"

LAYERDEPENDS_meta-textbook-sdk = "core"
LAYERSERIES_COMPAT_meta-textbook-sdk = "scarthgap"
